#!/usr/bin/env node
// Parses cherry-12-r.bdf and cherry-12-b.bdf into src/cherry-font.js.
// Run from the project root: node src/parse-bdf.js

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

function parseBDF(filePath) {
  const lines = readFileSync(filePath, 'utf8').split('\n');
  const glyphs = {};
  let encoding = null;
  let inBitmap = false;
  let rows = [];

  for (const raw of lines) {
    const t = raw.trim();
    if (t.startsWith('ENCODING ')) {
      encoding = parseInt(t.slice(9), 10);
    } else if (t === 'BITMAP') {
      inBitmap = true;
      rows = [];
    } else if (t === 'ENDCHAR') {
      if (encoding !== null) glyphs[encoding] = rows;
      encoding = null;
      inBitmap = false;
      rows = [];
    } else if (inBitmap && t.length > 0) {
      rows.push(parseInt(t, 16));
    }
  }
  return glyphs;
}

function serialize(glyphs) {
  const entries = Object.entries(glyphs)
    .sort(([a], [b]) => Number(a) - Number(b))
    .map(([cp, rows]) => `  ${cp}:[${rows.join(',')}]`)
    .join(',\n');
  return `{\n${entries}\n}`;
}

const regular = parseBDF(join(__dirname, 'cherry-12-r.bdf'));
const bold    = parseBDF(join(__dirname, 'cherry-12-b.bdf'));

const out = `// Generated by src/parse-bdf.js — do not edit by hand.
// Cherry 12px bitmap font (7 px wide × 12 px tall, monospace).
// Each entry: [r0,r1,...,r11] where each byte's MSB is the leftmost pixel.
export const CHERRY_R = ${serialize(regular)};

export const CHERRY_B = ${serialize(bold)};
`;

const outPath = join(__dirname, 'cherry-font.js');
writeFileSync(outPath, out, 'utf8');
console.log(`Wrote ${outPath} (${regular ? Object.keys(regular).length : 0} regular glyphs, ${bold ? Object.keys(bold).length : 0} bold glyphs)`);
